apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: c2vmwkakw-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-45baf196d1.246r.p3.openshiftapps.com/rhtap/rhtap-qe-nodejs:394a8032a64acc35bcb7ec5caa5ab9ac77e9f76c@sha256:77280964de14dd12f093ec0e39d721894b118f9f75feb90b616e9eeb6e24e129
          name: container-image
